[Service]
Environment="GF_SMTP_ENABLED=true"
Environment="GF_SMTP_HOST=smtp.yandex.ru:465"
Environment="GF_SMTP_USER=your-login@yandex.ru"
Environment="GF_SMTP_PASSWORD=xxxxxxxxxxxxxxxx"
Environment="GF_SMTP_FROM_ADDRESS=your-login@yandex.ru"
Environment="GF_SMTP_FROM_NAME=Grafana Alert"
Environment="GF_SMTP_SKIP_VERIFY=false"
