{
 "title": "Node Exporter — Netology HW14",
 "tags": [
  "netology",
  "node-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU utilization, % (100 - idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load Average 1 / 5 / 15",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "LA1 {{instance}}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "LA5 {{instance}}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "LA15 {{instance}}"
    }
   ]
  },
  {
   "title": "Free / available memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"nodeexporter\"}",
     "legendFormat": "available {{instance}}"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "free {{instance}}"
    }
   ]
  },
  {
   "title": "Free space on filesystems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexporter\",fstype!~\"tmpfs|overlay|squashfs|fuse.lxcfs|ramfs\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  }
 ]
}